### PR TITLE
Vardensity

### PR DESCRIPTION
**Pull request by yramachers**
This introduces another geometry command to the set the density [g/cm3] of the gas in the materials section. This allows scattering studies with variable gas density. Also the scoring energy deposit threshold was raised to 1 meV, avoiding spurious miniscule edep from single scattering in gas without any transport consequences (no deviation from straight line path).

### CODE REVIEW

**Comment by yramachers** [comment]
I am not too happy with the scoring. I'll might try something more compact and simpler instead of the 'primitive scorer' technique. I was interested in scoring the stop watch hit locations to check on small path deviations but scoring becomes more and more complicated when using many 'PS' scorers. Not ideal. Anyway, that would be done on a different PR.

**Comment by TomGoffrey** [comment]
Happy to merge this as it, although I'm wondering if it is worth adding the gas density to the command line arguments?

**Comment by yramachers** [comment]
I would prefer to keep genuine model parameter confined to the macro script rather than exposing them to the command line. The CLI should only feature code options like output file name and which script to run. The physics list of choice is also confined to a macro script whose name can then be given on the command line.

**Comment by TomGoffrey** [comment]
Yes that's reasonable.

**Review by TomGoffrey — APPROVED** [review]

**Pull request merged**
