### PR TITLE
E-gun

### PR DESCRIPTION
**Pull request by yramachers**
A new application example, simulating an electron gun at a given energy (default is 18.575 keV, change by macro) shooting into a 1 m long cylinder (diam: 10 cm) filled with Helium gas (Default STP density 1.66322e-4 g/ccm) at variable density (by macro). The target for this simulation is the number of scattered electrons (on He) into a defined angle range at a given He-gas density. The cylinder and electron momentum axis is the z-axis, with scoring of electron-He interactions which either deposit energy in a step or change the momentum direction vector. Deposited energy, kinetic energy post step and the direction vector are scored in a ROOT file. a short analysis script is also present to print summaries, given a ROOT output file.

### CODE REVIEW

**Comment by TomGoffrey** [comment]
@yramachers I'll review this properly when I'm back at work on Wednesday, but a few superficial points:

 - Is the passing of `seed+1234` deliberate in `CLHEP::HepRandom::setTheSeed(1234+seed);` ? I don't think it matters, but it appears to contradict the help string for the option.
 - The README file mentions the scattering executable: `./scattering -m run.mac`.

If you don't mind, I'll probably upload a python script to analyse the output in a separate PR.

**Comment by yramachers** [comment]
@TomGoffrey Thanks, yes, I just submitted a correction, updating the README and added the offset to the CLI help + comment in the source code. A zero seed leads to a runtime error. The easiest option was to set an offset integer to the seed. I tend to use the job counter variable for the Slurm batch job system and that counter starts at zero.
Anyway, yes, please, add a python script. I am also considering an additional function in the ROOT script to actually analyse the data for the target question. At the moment it merely prints out content of the files. Question is: how many electrons scatter in a given angle range of interest (and what kinetic energy do they have after that scatter).

**Comment by TomGoffrey** [comment]
I'm probably missing something obvious, but could you offer some advice on how to use the `analyse` function?

**Comment by yramachers** [comment]
@TomGoffrey You would call it interactively with a file name and an angle range. The angle range means 90 degrees +- range in degrees. The file name may look a little more mysterious? It is a text file containing all the ROOT files to read in and analyse, building a TChain. This is a typical effect of batch job running when you create many files as output, each from a single job. I suppose a simpler 'analyse_single()' function would also be useful to work with a single ROOT file.

**Comment by TomGoffrey** [comment]
Ahah, yes, it was the first argument I couldn't figure out. My first guess of passing the name of the ROOT file did not go well, as you might imagine.

**Review by TomGoffrey — APPROVED** [review]

**Pull request merged**
