### PR TITLE
Kimball

### PR DESCRIPTION
**Pull request by yramachers**
Add new features to E-Gun simulation. Features similar to Kimball e-gun example from catalogue. Energy value/uncertainty setting permitted, spot size too. Command examples in geant4 macro example. Added interaction location output in ROOT file.

### CODE REVIEW

**Comment by TomGoffrey** [comment]
@yramachers Does this exit cleanly for you? I'm seeing Invalid free errors during clean-up:

```
==27422== Invalid free() / delete / delete[] / realloc()
==27422==    at 0x4C3323B: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27422==    by 0x16F8A7: std::_Sp_counted_ptr<CLHEP::HepRandomEngine*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (shared_ptr_base.h:376)
==27422==    by 0x92000C0: CLHEP::RandGauss::~RandGauss() (in /home/tom/dev/geant4.10.07.p01-install/lib/libG4clhep.so)
==27422==    by 0x9202BC8: CLHEP::RandGaussQ::~RandGaussQ() (in /home/tom/dev/geant4.10.07.p01-install/lib/libG4clhep.so)
==27422==    by 0x16E4B7: EGPrimaryGeneratorAction::~EGPrimaryGeneratorAction() (EGPrimaryGeneratorAction.cc:44)
==27422==    by 0x16E4DF: EGPrimaryGeneratorAction::~EGPrimaryGeneratorAction() (EGPrimaryGeneratorAction.cc:45)
==27422==    by 0x54717EB: G4RunManager::~G4RunManager() (in /home/tom/dev/geant4.10.07.p01-install/lib/libG4run.so)
==27422==    by 0x5471B58: G4RunManager::~G4RunManager() (in /home/tom/dev/geant4.10.07.p01-install/lib/libG4run.so)
==27422==    by 0x11C2F1: main (egun.cc:101)
```

This is with Geant4 10.07.p01, on both both my Mac and my (Ubuntu) desktop. Not tested elsewhere.

**Comment by yramachers** [comment]
I use 10.7 from the CERN cvmfs and that exits cleanly. I run with /run/verbose 2 which has long outputs about memory management when shutting down and there is no hint at any problem.
I use that CLHEP random engine and the Geant4 random number machinery for the first time in this app, at least beyond the trivial UniformRand(). The latter sets itself up, but here I wanted to try some of the convenience random number tools on offer and they need some effort beyond the uniform rand function. Your observation points at a problem with the shared pointer to the default random engine which is then used with all random number functions in Geant4.
Don't know, I don't see problems but can't rule them out, especially since these random number functions must be thread-safe and on that issue I have to rely on Geant4. Before this example, I only used C++ std random number functions in Geant4 and didn't get any problems. I would prefer though to stick to using Geant4 random functions.

**Comment by yramachers** [comment]
Maybe try again. This time, using RandGauss without constructor/delete, should exit cleanly.

**Review by TomGoffrey — APPROVED** [review]

**Comment by TomGoffrey** [comment]
Looks good to me. Feel free to merge.

**Pull request merged**
