### PR TITLE
Feature/seb boris

### PR DESCRIPTION
**Pull request by sebj101**
Pull request to merge in the code for the Boris solver with main. The Boris solver currently exists separate to the existing solvers but is called in a similar fashion. The only change made to the code of others is a change in the return value of ExternalField's field calculation function. This is to ensure consistency between the various versions of evaluate_field_at_point

### CODE REVIEW

**Comment by yramachers** [comment]
Hi @TomGoffrey I requested a review from you simply because you'd know the solver best and some of your cpp branch is in this PR.

**Comment by TomGoffrey** [comment]
I'd rather see this PR merge in the Boris solver only - the cpp code really is very much WIP.

@sebj101 If you don't object, I'm going to close this PR and re-open with a branch which only contains your changes. Is that OK?

**Comment by sebj101** [comment]
Apologies @TomGoffrey, I forgot that the cpp code hadn't been pushed to main yet. Please feel free to do the above.

**Comment by TomGoffrey** [comment]
@sebj101 No problem. I've just pushed a branch `feature/seb_boris_clean` - could you open a PR for it please? I'm not sure I can act as a reviewer if I open the request myself.

**Comment by TomGoffrey** [comment]
See #19

**Pull request closed without merging**
