### PR TITLE
Cd109source

### PR DESCRIPTION
**Pull request by yramachers**
First working version of a new example Geant4 app, simulating a commercial Cd-109 conversion electron source. Two source geometries have been found with datasheets from two different manufacturers, Isotrak and QSA and are implemented. A single user command, switching between the two geometries, has been included. Scoring appears to take place correctly but needs more detailed checking. 
Another open issue at the moment is that the code exists with a segmentation error, apparently without any consequences since the output file is sane and memory deletion message appear fine. Not clear where that comes from, to be investigated.
This app requires a minimum Geant4 version 11.2 due to changes to ROOT output between 10.7 and 11.2 (and other changes).

### CODE REVIEW

**Comment by yramachers** [comment]
Sorry, @TomGoffrey , looks like all the last summer edits of the other repositories like your branches are also included in this PR, reflecting the history of testing aspects of QTNMsim creation. This PR does not contain code from your branches, merely the new project folder Cd109source.

**Comment by yramachers** [comment]
Segmentation fault has been removed: deleting the AnalysisManager in the Run destructor is wrong. Previously commented on this in QTNMsim. I suspect this is a remnant of the egun example for version 10.7. Maybe egun and scattering example should be updated to using G4 11.2; but not for this PR.

**Comment by TomGoffrey** [comment]
@yramachers Any objection to me replacing this PR with one from [tom/Cd109source](https://github.com/QTNM/Electron-Tracking/tree/tom/Cd109source)? It's the same change set as this, but with a cleaned up history.

**Comment by yramachers** [comment]
None at all, please feel free to action as you see fit. That muddled history was my fault.

**Pull request closed without merging**
